### ISSUE TITLE
Best

### ISSUE THREAD

**Issue by Mohammadshah69** [grammarly/grammarly-for-developers#493]
Best

_Originally posted by @Mohammadshah69 in https://github.com/grammarly/grammarly-for-developers/discussions/492#discussioncomment-4976034_

**Comment by Mohammadshah69** [comment]
> ```
>     Best
> ```
> 
> 
>      
>   
> 
> _Originally posted by @Mohammadshah69 in [#492 (reply in thread)](https://github.com/grammarly/grammarly-for-developers/discussions/492#discussioncomment-4976034)_

M

**Comment by Mohammadshah69** [comment]
> ```
>     Best
> ```
> 
> 
>      
>   
> 
> _Originally posted by @Mohammadshah69 in [#492 (reply in thread)](https://github.com/grammarly/grammarly-for-developers/discussions/492#discussioncomment-4976034)_

J

**Comment by cwatkins** [comment]
Hi @Mohammadshah69, 

First off, welcome to the community!  

If you're having an issue with the Grammarly SDK, please feel free to file an issue using one of [our templates](https://github.com/grammarly/grammarly-for-developers/issues/new/choose) so that we can help you as best as possible.

In the meantime, I'm going to close this issue.
